/**
 * The catalogue as data. `seed.ts` turns this into products, variants, inventory and reviews;
 * `scripts/fetch-catalog-images.mjs` reads the same `imageQuery` fields so the photography and
 * the product list can never drift apart.
 *
 * Brands are fictional house labels (NOVA, AXIOM, VECTOR, LUMEN, ORBIT, KESTREL) so nothing
 * here claims to be a real product.
 */

export type OptionDefinition = {
  name: string;
  values: string[];
};

export type VariantDefinition = {
  /** Values in the same order as the product's `options`. */
  optionValues: string[];
  /** Added to the product's base price, in minor units. May be negative. */
  priceDeltaMinor?: number;
  /** Units on hand. Deliberately varied so low-stock and out-of-stock states are reachable. */
  onHand: number;
  /** Index into the product's image list; lets a variant swap the hero shot. */
  imageIndex?: number;
};

export type ProductDefinition = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  categorySlug: string;
  priceMinor: number;
  compareAtPriceMinor?: number;
  rating: number;
  reviewCount: number;
  badge?: "New" | "Deal";
  blurb: string;
  specs: [label: string, value: string][];
  options: OptionDefinition[];
  variants: VariantDefinition[];
  /** Search phrases for the image fetcher, best first. */
  imageQuery: string[];
  /**
   * At least one of these must appear in a candidate photo's alt text. Without it the search
   * happily returns a mixing desk for "studio monitors" or a yoga mat for "VR headset".
   */
  imageSubject: string[];
};

export type CategoryDefinition = {
  slug: string;
  name: string;
  blurb: string;
  /** Existing vector art in `frontend/public/catalog/`, used as category art only. */
  icon: string;
};

export const CATEGORIES: CategoryDefinition[] = [
  { slug: "audio", name: "Audio", blurb: "Headphones, speakers and the amplification behind them.", icon: "c-display.svg" },
  { slug: "wearables", name: "Wearables", blurb: "Watches, bands and rings that track without shouting.", icon: "c-phone.svg" },
  { slug: "computing", name: "Computing", blurb: "Keyboards, docks and the desk hardware around them.", icon: "c-laptop.svg" },
  { slug: "cameras", name: "Cameras", blurb: "Bodies, glass and flight for people who shoot.", icon: "c-display.svg" },
  { slug: "smart-home", name: "Smart Home", blurb: "Light, climate and security that stay out of the way.", icon: "c-power.svg" },
  { slug: "gaming", name: "Gaming", blurb: "Input, immersion and handhelds built for latency.", icon: "c-laptop.svg" },
  { slug: "phones", name: "Phones", blurb: "Pocket hardware, from compact to folding.", icon: "c-phone.svg" },
  { slug: "laptops", name: "Laptops", blurb: "Portable machines for writing, building and rendering.", icon: "c-laptop.svg" },
  { slug: "tablets", name: "Tablets", blurb: "Slates for drawing, reading and focused work.", icon: "c-tablet.svg" },
  { slug: "displays", name: "TVs & Displays", blurb: "Panels and projection, from desk to wall.", icon: "c-display.svg" },
  { slug: "networking", name: "Networking", blurb: "Mesh, switching and travel routing that holds up.", icon: "c-router.svg" },
  { slug: "storage", name: "Storage", blurb: "Fast pocket drives and quiet drives that stay home.", icon: "c-storage.svg" },
  { slug: "power-accessories", name: "Power & Accessories", blurb: "Charging, cabling and the small parts that matter.", icon: "c-power.svg" },
];

/**
 * 57 products across the 13 categories.
 */
export const PRODUCTS: ProductDefinition[] = [
  // ---------------------------------------------------------------- audio
  {
    slug: "aura-anc-headphones",
    name: "Aura ANC Headphones",
    brand: "NOVA",
    category: "Audio",
    categorySlug: "audio",
    priceMinor: 24900,
    compareAtPriceMinor: 31900,
    rating: 4.7,
    reviewCount: 428,
    badge: "Deal",
    blurb: "Adaptive noise cancellation with a 40-hour battery and spatial audio that stays honest with acoustic recordings.",
    specs: [["Driver", "40 mm dynamic"], ["Battery", "40 hours, ANC on"], ["Weight", "268 g"], ["Charging", "USB-C, 5 min for 4 hours"], ["Codecs", "AAC, LDAC, aptX"]],
    options: [{ name: "Colour", values: ["Midnight", "Sandstone", "Slate"] }],
    variants: [
      { optionValues: ["Midnight"], onHand: 42, imageIndex: 0 },
      { optionValues: ["Sandstone"], onHand: 4, imageIndex: 1 },
      { optionValues: ["Slate"], onHand: 18, imageIndex: 2 },
    ],
    imageQuery: ["black over ear headphones white background", "wireless headphones product", "headphones on table"],
    imageSubject: ["headphone", "headset", "earphone"],
  },
  {
    slug: "aura-studio-monitors",
    name: "Aura Studio Monitors",
    brand: "LUMEN",
    category: "Audio",
    categorySlug: "audio",
    priceMinor: 42900,
    rating: 4.8,
    reviewCount: 96,
    blurb: "A near-field pair with a woven mid driver and room correction you set once and then forget about.",
    specs: [["Configuration", "2-way active"], ["Power", "80 W per side"], ["Response", "45 Hz to 22 kHz"], ["Inputs", "XLR, TRS, USB-C"]],
    options: [],
    variants: [{ optionValues: [], onHand: 23 }],
    imageQuery: ["studio monitor speaker", "bookshelf speaker", "loudspeaker on stand"],
    imageSubject: ["speaker", "loudspeaker"],
  },
  {
    slug: "pulse-buds-pro",
    name: "Pulse Buds Pro",
    brand: "NOVA",
    category: "Audio",
    categorySlug: "audio",
    priceMinor: 12900,
    compareAtPriceMinor: 15900,
    rating: 4.4,
    reviewCount: 587,
    badge: "Deal",
    blurb: "Vented in-ears that seal without pressure, in a case that survives a pocket full of keys.",
    specs: [["Battery", "8 hours plus 24 in the case"], ["Rating", "IPX5"], ["ANC", "Hybrid, three levels"], ["Weight", "4.6 g per bud"]],
    options: [{ name: "Colour", values: ["Chalk", "Graphite"] }],
    variants: [
      { optionValues: ["Chalk"], onHand: 61, imageIndex: 0 },
      { optionValues: ["Graphite"], onHand: 0, imageIndex: 1 },
    ],
    imageQuery: ["wireless earbuds charging case", "earbuds close up", "in ear headphones white"],
    imageSubject: ["earbud", "earphone", "headphone", "airpod"],
  },
  {
    slug: "orbit-soundbar-5",
    name: "Orbit Soundbar 5",
    brand: "ORBIT",
    category: "Audio",
    categorySlug: "audio",
    priceMinor: 34900,
    rating: 4.3,
    reviewCount: 174,
    blurb: "A single-cabinet bar that reads the room on setup and keeps dialogue above the score.",
    specs: [["Channels", "5.1.2 virtual"], ["Inputs", "eARC, optical"], ["Subwoofer", "Wireless, 6.5 in"], ["Width", "980 mm"]],
    options: [],
    variants: [{ optionValues: [], onHand: 15 }],
    imageQuery: ["sound bar speaker", "home theater speaker system", "black speaker under television"],
    imageSubject: ["speaker", "sound system"],
  },
  {
    slug: "aura-portable-dac",
    name: "Aura Portable DAC",
    brand: "VECTOR",
    category: "Audio",
    categorySlug: "audio",
    priceMinor: 8900,
    rating: 4.6,
    reviewCount: 112,
    badge: "New",
    blurb: "A thumb-sized amplifier that drives studio cans off a phone without carrying a battery of its own.",
    specs: [["Output", "2 Vrms balanced"], ["Formats", "32-bit / 384 kHz"], ["Connector", "USB-C"], ["Weight", "22 g"]],
    options: [],
    variants: [{ optionValues: [], onHand: 37 }],
    imageQuery: ["audio interface usb device", "headphone amplifier", "usb dongle adapter"],
    imageSubject: ["adapter", "dongle", "amplifier", "audio interface", "usb"],
  },

  // ------------------------------------------------------------ wearables
  {
    slug: "pulse-smartwatch-s3",
    name: "Pulse Smartwatch S3",
    brand: "AXIOM",
    category: "Wearables",
    categorySlug: "wearables",
    priceMinor: 32900,
    rating: 4.6,
    reviewCount: 312,
    badge: "New",
    blurb: "Always-on AMOLED, continuous heart-rate tracking and a week of battery when you leave the display dimmed.",
    specs: [["Display", "1.9 in AMOLED"], ["Battery", "7 days typical"], ["Rating", "10 ATM"], ["Sensors", "HR, SpO2, ECG, GPS"]],
    options: [
      { name: "Case", values: ["41 mm", "45 mm"] },
      { name: "Band", values: ["Woven", "Silicone"] },
    ],
    variants: [
      { optionValues: ["41 mm", "Woven"], onHand: 28, imageIndex: 0 },
      { optionValues: ["41 mm", "Silicone"], priceDeltaMinor: -2000, onHand: 34, imageIndex: 0 },
      { optionValues: ["45 mm", "Woven"], priceDeltaMinor: 3000, onHand: 12, imageIndex: 1 },
      { optionValues: ["45 mm", "Silicone"], priceDeltaMinor: 1000, onHand: 3, imageIndex: 1 },
    ],
    imageQuery: ["smartwatch on white background", "smart watch face close up", "wrist watch digital"],
    imageSubject: ["watch", "smartwatch"],
  },
  {
    slug: "pulse-band-lite",
    name: "Pulse Band Lite",
    brand: "NOVA",
    category: "Wearables",
    categorySlug: "wearables",
    priceMinor: 5900,
    compareAtPriceMinor: 7900,
    rating: 4.2,
    reviewCount: 401,
    badge: "Deal",
    blurb: "A 21-gram band that tracks sleep and steps for three weeks between charges.",
    specs: [["Display", "0.9 in AMOLED"], ["Battery", "21 days"], ["Rating", "5 ATM"], ["Weight", "21 g"]],
    options: [{ name: "Colour", values: ["Black", "Coral", "Mist"] }],
    variants: [
      { optionValues: ["Black"], onHand: 88, imageIndex: 0 },
      { optionValues: ["Coral"], onHand: 41, imageIndex: 1 },
      { optionValues: ["Mist"], onHand: 2, imageIndex: 2 },
    ],
    imageQuery: ["fitness tracker band", "activity wristband", "fitness band wrist"],
    imageSubject: ["band", "tracker", "watch", "bracelet"],
  },
  {
    slug: "axiom-ring-one",
    name: "Axiom Ring One",
    brand: "AXIOM",
    category: "Wearables",
    categorySlug: "wearables",
    priceMinor: 27900,
    rating: 4.1,
    reviewCount: 88,
    badge: "New",
    blurb: "Titanium sleep and recovery tracking for people who will not wear a watch to bed.",
    specs: [["Material", "Grade 5 titanium"], ["Battery", "6 days"], ["Sensors", "HR, temperature, SpO2"], ["Sizes", "6 to 13"]],
    options: [{ name: "Finish", values: ["Brushed", "Matte Black"] }],
    variants: [
      { optionValues: ["Brushed"], onHand: 19, imageIndex: 0 },
      { optionValues: ["Matte Black"], priceDeltaMinor: 2000, onHand: 7, imageIndex: 1 },
    ],
    imageQuery: ["ring on finger close up", "metal ring jewelry", "silver ring product"],
    imageSubject: ["ring"],
  },
  {
    slug: "kestrel-sport-watch",
    name: "Kestrel Sport Watch",
    brand: "KESTREL",
    category: "Wearables",
    categorySlug: "wearables",
    priceMinor: 45900,
    rating: 4.7,
    reviewCount: 143,
    blurb: "Dual-band GPS and a transflective display you can still read at hour nine in full sun.",
    specs: [["Display", "1.3 in transflective"], ["Battery", "40 hours with GPS"], ["Rating", "10 ATM"], ["Weight", "53 g"]],
    options: [],
    variants: [{ optionValues: [], onHand: 26 }],
    imageQuery: ["sports watch wrist outdoor", "gps running watch", "rugged watch close up"],
    imageSubject: ["watch"],
  },

  // ------------------------------------------------------------ computing
  {
    slug: "vector-65-keyboard",
    name: "Vector 65 Keyboard",
    brand: "VECTOR",
    category: "Computing",
    categorySlug: "computing",
    priceMinor: 17900,
    compareAtPriceMinor: 20900,
    rating: 4.5,
    reviewCount: 196,
    badge: "Deal",
    blurb: "Hot-swappable switches, a gasket-mounted aluminium case and a sound profile closer to thock than click.",
    specs: [["Layout", "65 percent, 68 keys"], ["Mount", "Gasket"], ["Case", "CNC aluminium"], ["Connection", "USB-C, BT 5.2, 2.4 GHz"]],
    options: [{ name: "Switch", values: ["Linear", "Tactile", "Silent"] }],
    variants: [
      { optionValues: ["Linear"], onHand: 44, imageIndex: 0 },
      { optionValues: ["Tactile"], onHand: 31, imageIndex: 1 },
      { optionValues: ["Silent"], priceDeltaMinor: 1500, onHand: 5, imageIndex: 2 },
    ],
    imageQuery: ["mechanical keyboard close up", "compact keyboard white background", "keyboard keycaps macro"],
    imageSubject: ["keyboard", "keycap"],
  },
  {
    slug: "vector-tkl-silent",
    name: "Vector TKL Silent",
    brand: "VECTOR",
    category: "Computing",
    categorySlug: "computing",
    priceMinor: 21900,
    rating: 4.4,
    reviewCount: 77,
    blurb: "A tenkeyless board with dampened stabilisers, built for open-plan offices and late calls.",
    specs: [["Layout", "TKL, 87 keys"], ["Mount", "Top, dampened"], ["Case", "Aluminium"], ["Connection", "USB-C"]],
    options: [],
    variants: [{ optionValues: [], onHand: 29 }],
    imageQuery: ["white keyboard on desk", "keyboard top view", "computer keyboard product"],
    imageSubject: ["keyboard", "keycap"],
  },
  {
    slug: "paper-reader-air",
    name: "Paper Reader Air",
    brand: "NOVA",
    category: "Computing",
    categorySlug: "computing",
    priceMinor: 19900,
    rating: 4.4,
    reviewCount: 203,
    blurb: "Glare-free 300 ppi, a warm front light and weeks of reading between charges.",
    specs: [["Display", "7 in, 300 ppi"], ["Light", "Warm and cool"], ["Storage", "32 GB"], ["Battery", "6 weeks"]],
    options: [],
    variants: [{ optionValues: [], onHand: 47 }],
    imageQuery: ["e reader in hands", "ebook reader on table", "e ink reader"],
    imageSubject: ["reader", "kindle", "ebook", "e-book", "tablet"],
  },
  {
    slug: "nova-usb-c-dock",
    name: "Nova USB-C Dock",
    brand: "NOVA",
    category: "Computing",
    categorySlug: "computing",
    priceMinor: 15900,
    compareAtPriceMinor: 18900,
    rating: 4.3,
    reviewCount: 224,
    badge: "Deal",
    blurb: "One cable for two displays, wired network and 100 W back to the laptop.",
    specs: [["Ports", "11"], ["Displays", "2 x 4K 60 Hz"], ["Power", "100 W PD passthrough"], ["Network", "2.5 GbE"]],
    options: [],
    variants: [{ optionValues: [], onHand: 52 }],
    imageQuery: ["usb hub adapter", "usb c dock device", "adapter with cables"],
    imageSubject: ["hub", "dock", "adapter", "usb", "port"],
  },
  {
    slug: "vector-webcam-4k",
    name: "Vector Webcam 4K",
    brand: "VECTOR",
    category: "Computing",
    categorySlug: "computing",
    priceMinor: 13900,
    rating: 4.2,
    reviewCount: 158,
    blurb: "A one-inch sensor that holds skin tone in a badly lit room, with a shutter you can see.",
    specs: [["Sensor", "1 in CMOS"], ["Video", "4K 30 or 1080p 60"], ["Field of view", "78 degrees"], ["Mic", "Dual, noise-gated"]],
    options: [],
    variants: [{ optionValues: [], onHand: 33 }],
    imageQuery: ["webcam", "web camera for computer", "webcam on top of monitor"],
    imageSubject: ["webcam", "web camera"],
  },

  // -------------------------------------------------------------- cameras
  {
    slug: "lumen-mirrorless-x",
    name: "Lumen Mirrorless X",
    brand: "LUMEN",
    category: "Cameras",
    categorySlug: "cameras",
    priceMinor: 128900,
    rating: 4.9,
    reviewCount: 88,
    blurb: "A full-frame 33 MP body with in-body stabilisation and open-gate 6K video.",
    specs: [["Sensor", "33 MP full-frame"], ["Video", "6K 30p open gate"], ["Stabilisation", "5-axis IBIS"], ["Mount", "Universal E"], ["Slots", "Dual UHS-II"]],
    options: [{ name: "Kit", values: ["Body only", "With 28-70 mm"] }],
    variants: [
      { optionValues: ["Body only"], onHand: 11, imageIndex: 0 },
      { optionValues: ["With 28-70 mm"], priceDeltaMinor: 42000, onHand: 4, imageIndex: 1 },
    ],
    imageQuery: ["mirrorless camera on table", "camera body close up", "camera white background"],
    imageSubject: ["camera"],
  },
  {
    slug: "skyline-drone-pro",
    name: "Skyline Drone Pro",
    brand: "KESTREL",
    category: "Cameras",
    categorySlug: "cameras",
    priceMinor: 89900,
    rating: 4.6,
    reviewCount: 141,
    badge: "New",
    blurb: "Obstacle-aware flight with a one-inch gimbal sensor and 42 minutes of airtime per charge.",
    specs: [["Airtime", "42 min"], ["Sensor", "1 in CMOS"], ["Range", "12 km"], ["Weight", "595 g"]],
    options: [{ name: "Bundle", values: ["Standard", "Fly More"] }],
    variants: [
      { optionValues: ["Standard"], onHand: 14, imageIndex: 0 },
      { optionValues: ["Fly More"], priceDeltaMinor: 28000, onHand: 6, imageIndex: 1 },
    ],
    imageQuery: ["drone flying", "quadcopter drone close up", "drone on ground"],
    imageSubject: ["drone", "quadcopter"],
  },
  {
    slug: "lumen-compact-z",
    name: "Lumen Compact Z",
    brand: "LUMEN",
    category: "Cameras",
    categorySlug: "cameras",
    priceMinor: 64900,
    compareAtPriceMinor: 72900,
    rating: 4.5,
    reviewCount: 127,
    badge: "Deal",
    blurb: "A coat-pocket camera with a fast zoom, for the days you will not carry a bag.",
    specs: [["Sensor", "20 MP 1 in"], ["Lens", "24-70 mm f/1.8-2.8"], ["Viewfinder", "Pop-up OLED"], ["Weight", "302 g"]],
    options: [],
    variants: [{ optionValues: [], onHand: 21 }],
    imageQuery: ["compact camera in hand", "point and shoot camera", "small camera product"],
    imageSubject: ["camera"],
  },
  {
    slug: "kestrel-action-cam",
    name: "Kestrel Action Cam",
    brand: "KESTREL",
    category: "Cameras",
    categorySlug: "cameras",
    priceMinor: 32900,
    rating: 4.3,
    reviewCount: 264,
    blurb: "Waterproof to 12 metres without a housing, with horizon lock that holds through a tumble.",
    specs: [["Video", "5.3K 60p"], ["Waterproof", "12 m"], ["Stabilisation", "Horizon lock"], ["Weight", "154 g"]],
    options: [{ name: "Bundle", values: ["Camera only", "Adventure kit"] }],
    variants: [
      { optionValues: ["Camera only"], onHand: 38, imageIndex: 0 },
      { optionValues: ["Adventure kit"], priceDeltaMinor: 9000, onHand: 16, imageIndex: 1 },
    ],
    imageQuery: ["action camera close up", "waterproof camera", "action cam on mount"],
    imageSubject: ["camera", "action cam", "gopro"],
  },
  {
    slug: "lumen-prime-35",
    name: "Lumen Prime 35 mm",
    brand: "LUMEN",
    category: "Cameras",
    categorySlug: "cameras",
    priceMinor: 47900,
    rating: 4.8,
    reviewCount: 64,
    blurb: "A fast 35 that stays sharp wide open, weather-sealed and quiet enough to film with.",
    specs: [["Focal length", "35 mm"], ["Aperture", "f/1.4"], ["Elements", "11 in 9 groups"], ["Filter", "67 mm"], ["Weight", "465 g"]],
    options: [],
    variants: [{ optionValues: [], onHand: 9 }],
    imageQuery: ["camera lens close up", "photography lens on table", "lens white background"],
    imageSubject: ["lens"],
  },

  // ----------------------------------------------------------- smart-home
  {
    slug: "orbit-smart-speaker",
    name: "Orbit Smart Speaker",
    brand: "ORBIT",
    category: "Smart Home",
    categorySlug: "smart-home",
    priceMinor: 14900,
    compareAtPriceMinor: 18900,
    rating: 4.4,
    reviewCount: 254,
    badge: "Deal",
    blurb: "Room-filling 360-degree sound with on-device voice processing, so nothing leaves your home network.",
    specs: [["Output", "60 W"], ["Drivers", "360 degree array"], ["Voice", "On-device"], ["Mesh", "Multi-room"]],
    options: [{ name: "Colour", values: ["Charcoal", "Linen"] }],
    variants: [
      { optionValues: ["Charcoal"], onHand: 46, imageIndex: 0 },
      { optionValues: ["Linen"], onHand: 22, imageIndex: 1 },
    ],
    imageQuery: ["smart speaker on shelf", "voice assistant speaker", "fabric speaker product"],
    imageSubject: ["speaker"],
  },
  {
    slug: "halo-desk-lamp",
    name: "Halo Desk Lamp",
    brand: "ORBIT",
    category: "Smart Home",
    categorySlug: "smart-home",
    priceMinor: 12900,
    compareAtPriceMinor: 15900,
    rating: 4.4,
    reviewCount: 164,
    badge: "Deal",
    blurb: "Circadian lighting that shifts temperature through the day, controlled from any device.",
    specs: [["Output", "800 lumens"], ["Temperature", "2200 to 6500 K"], ["Control", "App and touch"], ["Finish", "Matte alloy"]],
    options: [{ name: "Finish", values: ["Graphite", "Bone"] }],
    variants: [
      { optionValues: ["Graphite"], onHand: 35, imageIndex: 0 },
      { optionValues: ["Bone"], onHand: 8, imageIndex: 1 },
    ],
    imageQuery: ["desk lamp on table", "modern table lamp", "led lamp close up"],
    imageSubject: ["lamp", "light"],
  },
  {
    slug: "orbit-door-cam",
    name: "Orbit Door Cam",
    brand: "ORBIT",
    category: "Smart Home",
    categorySlug: "smart-home",
    priceMinor: 17900,
    rating: 4.2,
    reviewCount: 192,
    blurb: "Head-to-toe framing, local recording to a card, and no subscription to see yesterday.",
    specs: [["Video", "2K HDR"], ["Field of view", "160 degrees vertical"], ["Storage", "Local microSD"], ["Power", "Wired or battery"]],
    options: [],
    variants: [{ optionValues: [], onHand: 31 }],
    imageQuery: ["video doorbell on wall", "security camera outdoor", "doorbell camera close up"],
    imageSubject: ["doorbell", "camera", "intercom"],
  },
  {
    slug: "orbit-thermostat",
    name: "Orbit Thermostat",
    brand: "ORBIT",
    category: "Smart Home",
    categorySlug: "smart-home",
    priceMinor: 19900,
    rating: 4.5,
    reviewCount: 138,
    badge: "New",
    blurb: "Learns the house rather than the schedule, and works offline when the internet does not.",
    specs: [["Display", "2.4 in colour"], ["Sensors", "Temperature, humidity, presence"], ["Radios", "Matter, Thread, Wi-Fi"], ["Offline", "Full local control"]],
    options: [],
    variants: [{ optionValues: [], onHand: 27 }],
    imageQuery: ["smart thermostat on wall", "thermostat close up", "temperature control device"],
    imageSubject: ["thermostat", "heating", "temperature"],
  },
  {
    slug: "orbit-smart-bulbs-4",
    name: "Orbit Smart Bulbs 4-Pack",
    brand: "ORBIT",
    category: "Smart Home",
    categorySlug: "smart-home",
    priceMinor: 6900,
    compareAtPriceMinor: 8900,
    rating: 4.1,
    reviewCount: 356,
    badge: "Deal",
    blurb: "Full-colour bulbs that pair over Matter in one tap and hold their scene after a power cut.",
    specs: [["Brightness", "1100 lumens"], ["Colour", "16 million plus tunable white"], ["Protocol", "Matter over Thread"], ["Fitting", "E27"]],
    options: [{ name: "Fitting", values: ["E27", "GU10"] }],
    variants: [
      { optionValues: ["E27"], onHand: 74, imageIndex: 0 },
      { optionValues: ["GU10"], onHand: 0, imageIndex: 1 },
    ],
    imageQuery: ["light bulb close up", "led bulb product", "smart bulb on white"],
    imageSubject: ["bulb", "lamp", "light"],
  },

  // --------------------------------------------------------------- gaming
  {
    slug: "glide-precision-mouse",
    name: "Glide Precision Mouse",
    brand: "VECTOR",
    category: "Gaming",
    categorySlug: "gaming",
    priceMinor: 8900,
    compareAtPriceMinor: 10900,
    rating: 4.5,
    reviewCount: 372,
    badge: "Deal",
    blurb: "A 26K optical sensor in a 54-gram shell, on an 8000 Hz wireless link built for competitive play.",
    specs: [["Sensor", "26K DPI"], ["Weight", "54 g"], ["Polling", "8000 Hz"], ["Battery", "90 hours"]],
    options: [{ name: "Colour", values: ["Black", "White"] }],
    variants: [
      { optionValues: ["Black"], onHand: 58, imageIndex: 0 },
      { optionValues: ["White"], onHand: 12, imageIndex: 1 },
    ],
    imageQuery: ["computer mouse close up", "gaming mouse white background", "wireless mouse on desk"],
    imageSubject: ["mouse"],
  },
  {
    slug: "horizon-vr-headset",
    name: "Horizon VR Headset",
    brand: "AXIOM",
    category: "Gaming",
    categorySlug: "gaming",
    priceMinor: 54900,
    rating: 4.3,
    reviewCount: 117,
    badge: "New",
    blurb: "Pancake optics, inside-out tracking and 120 Hz per eye with no external base stations.",
    specs: [["Resolution", "2160 x 2160 per eye"], ["Refresh", "120 Hz"], ["Optics", "Pancake"], ["Tracking", "Inside-out"]],
    options: [{ name: "Storage", values: ["128 GB", "512 GB"] }],
    variants: [
      { optionValues: ["128 GB"], onHand: 17, imageIndex: 0 },
      { optionValues: ["512 GB"], priceDeltaMinor: 12000, onHand: 5, imageIndex: 0 },
    ],
    imageQuery: ["vr headset close up", "virtual reality goggles", "person wearing vr headset"],
    imageSubject: ["vr", "virtual reality", "headset", "goggles"],
  },
  {
    slug: "vector-gamepad-pro",
    name: "Vector Gamepad Pro",
    brand: "VECTOR",
    category: "Gaming",
    categorySlug: "gaming",
    priceMinor: 14900,
    rating: 4.6,
    reviewCount: 208,
    blurb: "Hall-effect sticks that will not drift, four back paddles and swappable stick heights.",
    specs: [["Sticks", "Hall effect"], ["Triggers", "Analogue with stops"], ["Paddles", "4, remappable"], ["Battery", "35 hours"]],
    options: [{ name: "Colour", values: ["Black", "Sand"] }],
    variants: [
      { optionValues: ["Black"], onHand: 40, imageIndex: 0 },
      { optionValues: ["Sand"], onHand: 3, imageIndex: 1 },
    ],
    imageQuery: ["game controller close up", "gamepad white background", "video game controller in hands"],
    imageSubject: ["controller", "gamepad", "joystick"],
  },
  {
    slug: "glide-xl-deskmat",
    name: "Glide XL Deskmat",
    brand: "VECTOR",
    category: "Gaming",
    categorySlug: "gaming",
    priceMinor: 3900,
    rating: 4.4,
    reviewCount: 431,
    blurb: "A stitched-edge cloth mat that stays flat out of the tube and washes without curling.",
    specs: [["Size", "900 x 400 mm"], ["Thickness", "4 mm"], ["Surface", "Fine-weave cloth"], ["Base", "Textured rubber"]],
    options: [{ name: "Size", values: ["900 x 400", "1200 x 600"] }],
    variants: [
      { optionValues: ["900 x 400"], onHand: 96, imageIndex: 0 },
      { optionValues: ["1200 x 600"], priceDeltaMinor: 1500, onHand: 44, imageIndex: 1 },
    ],
    imageQuery: ["desk mat with keyboard and mouse", "mouse pad on desk", "desk setup top view"],
    imageSubject: ["mat", "pad", "desk", "keyboard", "mouse"],
  },
  {
    slug: "axiom-handheld-go",
    name: "Axiom Handheld Go",
    brand: "AXIOM",
    category: "Gaming",
    categorySlug: "gaming",
    priceMinor: 69900,
    compareAtPriceMinor: 79900,
    rating: 4.2,
    reviewCount: 96,
    badge: "Deal",
    blurb: "A 7-inch handheld PC that runs your existing library, with a fan you can actually ignore.",
    specs: [["Display", "7 in 1200p 120 Hz"], ["Memory", "16 GB LPDDR5"], ["Storage", "1 TB NVMe"], ["Battery", "49 Wh"]],
    options: [{ name: "Storage", values: ["512 GB", "1 TB"] }],
    variants: [
      { optionValues: ["512 GB"], priceDeltaMinor: -10000, onHand: 13, imageIndex: 0 },
      { optionValues: ["1 TB"], onHand: 8, imageIndex: 0 },
    ],
    imageQuery: ["handheld game console", "portable console in hands", "retro handheld device"],
    imageSubject: ["handheld", "console", "gaming"],
  },

  // --------------------------------------------------------------- phones
  {
    slug: "nova-x1-phone",
    name: "Nova X1 Phone",
    brand: "NOVA",
    category: "Phones",
    categorySlug: "phones",
    priceMinor: 79900,
    compareAtPriceMinor: 89900,
    rating: 4.6,
    reviewCount: 286,
    badge: "Deal",
    blurb: "A bright 6.7-inch OLED phone with a 50 MP stabilised camera and two-day battery life.",
    specs: [["Display", "6.7 in OLED 120 Hz"], ["Camera", "50 MP OIS"], ["Battery", "5100 mAh"], ["Charging", "80 W wired"], ["Rating", "IP68"]],
    options: [
      { name: "Colour", values: ["Obsidian", "Fog"] },
      { name: "Storage", values: ["256 GB", "512 GB"] },
    ],
    variants: [
      { optionValues: ["Obsidian", "256 GB"], onHand: 33, imageIndex: 0 },
      { optionValues: ["Obsidian", "512 GB"], priceDeltaMinor: 10000, onHand: 15, imageIndex: 0 },
      { optionValues: ["Fog", "256 GB"], onHand: 21, imageIndex: 1 },
      { optionValues: ["Fog", "512 GB"], priceDeltaMinor: 10000, onHand: 2, imageIndex: 1 },
    ],
    imageQuery: ["smartphone on white background", "mobile phone in hand", "phone screen close up"],
    imageSubject: ["phone", "smartphone", "mobile"],
  },
  {
    slug: "axiom-fold-mini",
    name: "Axiom Fold Mini",
    brand: "AXIOM",
    category: "Phones",
    categorySlug: "phones",
    priceMinor: 119900,
    rating: 4.2,
    reviewCount: 94,
    badge: "New",
    blurb: "A pocketable foldable with a full-size inner display and a cover screen that is worth using.",
    specs: [["Inner display", "7.1 in OLED"], ["Cover display", "3.6 in OLED"], ["Hinge", "Rated 400,000 folds"], ["Battery", "4400 mAh"]],
    options: [
      { name: "Colour", values: ["Ink", "Blush"] },
      { name: "Storage", values: ["256 GB", "512 GB"] },
    ],
    variants: [
      { optionValues: ["Ink", "256 GB"], onHand: 9, imageIndex: 0 },
      { optionValues: ["Ink", "512 GB"], priceDeltaMinor: 12000, onHand: 6, imageIndex: 0 },
      { optionValues: ["Blush", "256 GB"], onHand: 4, imageIndex: 1 },
      { optionValues: ["Blush", "512 GB"], priceDeltaMinor: 12000, onHand: 0, imageIndex: 1 },
    ],
    imageQuery: ["foldable phone", "folding smartphone open", "flip phone modern"],
    imageSubject: ["phone", "foldable", "folding", "flip"],
  },
  {
    slug: "nova-x1-pro-phone",
    name: "Nova X1 Pro Phone",
    brand: "NOVA",
    category: "Phones",
    categorySlug: "phones",
    priceMinor: 109900,
    rating: 4.7,
    reviewCount: 152,
    badge: "New",
    blurb: "The X1 with a periscope tele, a brighter panel and the vapour chamber that comes with both.",
    specs: [["Display", "6.8 in LTPO, 2600 nits"], ["Camera", "50 MP main, 5x periscope"], ["Battery", "5400 mAh"], ["Charging", "100 W wired, 50 W wireless"]],
    options: [
      { name: "Colour", values: ["Obsidian", "Bronze"] },
      { name: "Storage", values: ["512 GB", "1 TB"] },
    ],
    variants: [
      { optionValues: ["Obsidian", "512 GB"], onHand: 18, imageIndex: 0 },
      { optionValues: ["Obsidian", "1 TB"], priceDeltaMinor: 15000, onHand: 7, imageIndex: 0 },
      { optionValues: ["Bronze", "512 GB"], onHand: 11, imageIndex: 1 },
      { optionValues: ["Bronze", "1 TB"], priceDeltaMinor: 15000, onHand: 3, imageIndex: 1 },
    ],
    imageQuery: ["smartphone camera back", "phone rear cameras close up", "premium smartphone product"],
    imageSubject: ["phone", "smartphone"],
  },
  {
    slug: "axiom-lite-5g",
    name: "Axiom Lite 5G",
    brand: "AXIOM",
    category: "Phones",
    categorySlug: "phones",
    priceMinor: 29900,
    compareAtPriceMinor: 34900,
    rating: 4.0,
    reviewCount: 318,
    badge: "Deal",
    blurb: "The phone to hand someone who wants four years of updates and does not care about benchmarks.",
    specs: [["Display", "6.5 in LCD 90 Hz"], ["Camera", "50 MP main"], ["Battery", "5000 mAh"], ["Updates", "4 years OS, 5 security"]],
    options: [{ name: "Colour", values: ["Slate", "Sky"] }],
    variants: [
      { optionValues: ["Slate"], onHand: 64, imageIndex: 0 },
      { optionValues: ["Sky"], onHand: 39, imageIndex: 1 },
    ],
    imageQuery: ["smartphone white background", "mobile phone in hand front", "smartphone product photo"],
    imageSubject: ["phone", "smartphone"],
  },

  // -------------------------------------------------------------- laptops
  {
    slug: "vector-studio-14",
    name: "Vector Studio 14",
    brand: "VECTOR",
    category: "Laptops",
    categorySlug: "laptops",
    priceMinor: 149900,
    compareAtPriceMinor: 169900,
    rating: 4.8,
    reviewCount: 173,
    badge: "Deal",
    blurb: "A quiet aluminium workstation with a colour-accurate 120 Hz display and all-day performance.",
    specs: [["Display", "14.5 in 3K 120 Hz"], ["Colour", "100 percent DCI-P3"], ["Ports", "2 x TB4, HDMI, SD"], ["Weight", "1.42 kg"], ["Battery", "72 Wh"]],
    options: [
      { name: "Memory", values: ["16 GB", "32 GB"] },
      { name: "Storage", values: ["512 GB", "1 TB"] },
    ],
    variants: [
      { optionValues: ["16 GB", "512 GB"], priceDeltaMinor: -20000, onHand: 12, imageIndex: 0 },
      { optionValues: ["16 GB", "1 TB"], priceDeltaMinor: -10000, onHand: 9, imageIndex: 0 },
      { optionValues: ["32 GB", "512 GB"], priceDeltaMinor: -5000, onHand: 6, imageIndex: 0 },
      { optionValues: ["32 GB", "1 TB"], onHand: 4, imageIndex: 1 },
    ],
    imageQuery: ["laptop on desk open", "laptop computer product", "laptop screen close up"],
    imageSubject: ["laptop", "notebook", "macbook"],
  },
  {
    slug: "nova-airbook-13",
    name: "Nova Airbook 13",
    brand: "NOVA",
    category: "Laptops",
    categorySlug: "laptops",
    priceMinor: 99900,
    rating: 4.4,
    reviewCount: 221,
    badge: "New",
    blurb: "A thin everyday laptop balancing a crisp display, responsive performance and 18-hour battery.",
    specs: [["Display", "13.6 in 2.5K"], ["Weight", "1.19 kg"], ["Battery", "Up to 18 hours"], ["Ports", "2 x USB-C, headphone"]],
    options: [
      { name: "Memory", values: ["16 GB", "24 GB"] },
      { name: "Storage", values: ["512 GB", "1 TB"] },
    ],
    variants: [
      { optionValues: ["16 GB", "512 GB"], onHand: 26, imageIndex: 0 },
      { optionValues: ["16 GB", "1 TB"], priceDeltaMinor: 12000, onHand: 14, imageIndex: 0 },
      { optionValues: ["24 GB", "512 GB"], priceDeltaMinor: 10000, onHand: 8, imageIndex: 1 },
      { optionValues: ["24 GB", "1 TB"], priceDeltaMinor: 22000, onHand: 5, imageIndex: 1 },
    ],
    imageQuery: ["thin laptop closed", "silver laptop on table", "laptop white background"],
    imageSubject: ["laptop", "notebook", "macbook"],
  },
  {
    slug: "vector-studio-16",
    name: "Vector Studio 16",
    brand: "VECTOR",
    category: "Laptops",
    categorySlug: "laptops",
    priceMinor: 219900,
    rating: 4.7,
    reviewCount: 61,
    blurb: "The 16-inch chassis for renders that run overnight, with the thermal headroom to match.",
    specs: [["Display", "16 in 4K mini-LED"], ["GPU", "Discrete, 12 GB"], ["Ports", "3 x TB4, HDMI 2.1, SD"], ["Weight", "2.1 kg"]],
    options: [
      { name: "Memory", values: ["32 GB", "64 GB"] },
      { name: "Storage", values: ["1 TB", "2 TB"] },
    ],
    variants: [
      { optionValues: ["32 GB", "1 TB"], onHand: 7, imageIndex: 0 },
      { optionValues: ["32 GB", "2 TB"], priceDeltaMinor: 20000, onHand: 3, imageIndex: 0 },
      { optionValues: ["64 GB", "1 TB"], priceDeltaMinor: 30000, onHand: 2, imageIndex: 0 },
      { optionValues: ["64 GB", "2 TB"], priceDeltaMinor: 50000, onHand: 0, imageIndex: 0 },
    ],
    imageQuery: ["large laptop on desk", "laptop workstation", "laptop keyboard close up"],
    imageSubject: ["laptop", "notebook", "macbook"],
  },
  {
    slug: "axiom-chrome-14",
    name: "Axiom Chrome 14",
    brand: "AXIOM",
    category: "Laptops",
    categorySlug: "laptops",
    priceMinor: 44900,
    compareAtPriceMinor: 52900,
    rating: 4.1,
    reviewCount: 187,
    badge: "Deal",
    blurb: "A browser-first laptop that boots in seconds and survives a school bag.",
    specs: [["Display", "14 in 1080p touch"], ["Memory", "8 GB"], ["Storage", "128 GB eMMC"], ["Battery", "Up to 13 hours"]],
    options: [],
    variants: [{ optionValues: [], onHand: 43 }],
    imageQuery: ["laptop white background", "open laptop on desk", "laptop computer close up"],
    imageSubject: ["laptop"],
  },

  // -------------------------------------------------------------- tablets
  {
    slug: "lumen-canvas-tab",
    name: "Lumen Canvas Tab",
    brand: "LUMEN",
    category: "Tablets",
    categorySlug: "tablets",
    priceMinor: 64900,
    compareAtPriceMinor: 72900,
    rating: 4.6,
    reviewCount: 138,
    badge: "Deal",
    blurb: "A high-refresh tablet for illustration, entertainment and focused work, with the pen included.",
    specs: [["Display", "12.4 in 144 Hz"], ["Pen", "Included, 4096 levels"], ["Battery", "11,200 mAh"], ["Speakers", "Quad"]],
    options: [{ name: "Storage", values: ["128 GB", "256 GB", "512 GB"] }],
    variants: [
      { optionValues: ["128 GB"], priceDeltaMinor: -8000, onHand: 24, imageIndex: 0 },
      { optionValues: ["256 GB"], onHand: 17, imageIndex: 0 },
      { optionValues: ["512 GB"], priceDeltaMinor: 12000, onHand: 5, imageIndex: 1 },
    ],
    imageQuery: ["tablet with stylus", "tablet on desk", "drawing tablet in hands"],
    imageSubject: ["tablet", "ipad"],
  },
  {
    slug: "paper-note-pro",
    name: "Paper Note Pro",
    brand: "NOVA",
    category: "Tablets",
    categorySlug: "tablets",
    priceMinor: 44900,
    rating: 4.3,
    reviewCount: 87,
    badge: "New",
    blurb: "A distraction-free paper tablet with a low-latency pen and a glare-free writing surface.",
    specs: [["Display", "10.3 in e-paper"], ["Pen latency", "18 ms"], ["Storage", "64 GB"], ["Weight", "405 g"]],
    options: [{ name: "Cover", values: ["None", "Folio"] }],
    variants: [
      { optionValues: ["None"], onHand: 29, imageIndex: 0 },
      { optionValues: ["Folio"], priceDeltaMinor: 5900, onHand: 11, imageIndex: 1 },
    ],
    imageQuery: ["e ink tablet writing", "digital notepad stylus", "e paper tablet"],
    imageSubject: ["tablet", "e ink", "e-ink", "notepad", "reader"],
  },
  {
    slug: "lumen-canvas-mini",
    name: "Lumen Canvas Mini",
    brand: "LUMEN",
    category: "Tablets",
    categorySlug: "tablets",
    priceMinor: 39900,
    rating: 4.4,
    reviewCount: 112,
    blurb: "An 8.7-inch slate that fits a jacket pocket and still runs the pen.",
    specs: [["Display", "8.7 in 120 Hz"], ["Weight", "297 g"], ["Battery", "6800 mAh"], ["Cellular", "Optional 5G"]],
    options: [{ name: "Storage", values: ["128 GB", "256 GB"] }],
    variants: [
      { optionValues: ["128 GB"], onHand: 36, imageIndex: 0 },
      { optionValues: ["256 GB"], priceDeltaMinor: 6000, onHand: 4, imageIndex: 0 },
    ],
    imageQuery: ["digital tablet device", "tablet computer with stylus", "person using a tablet"],
    imageSubject: ["tablet", "ipad"],
  },

  // ------------------------------------------------------------- displays
  {
    slug: "lumen-oled-32",
    name: "Lumen OLED 32 Monitor",
    brand: "LUMEN",
    category: "TVs & Displays",
    categorySlug: "displays",
    priceMinor: 109900,
    compareAtPriceMinor: 129900,
    rating: 4.8,
    reviewCount: 152,
    badge: "Deal",
    blurb: "A 4K OLED desktop display with true blacks, 240 Hz motion and one-cable laptop docking.",
    specs: [["Panel", "31.5 in 4K OLED"], ["Refresh", "240 Hz"], ["Ports", "USB-C 90 W, HDMI 2.1"], ["Colour", "99 percent DCI-P3"]],
    options: [],
    variants: [{ optionValues: [], onHand: 13 }],
    imageQuery: ["computer monitor front view", "gaming monitor on desk", "monitor screen dark room"],
    imageSubject: ["monitor", "display"],
  },
  {
    slug: "horizon-mini-projector",
    name: "Horizon Mini Projector",
    brand: "AXIOM",
    category: "TVs & Displays",
    categorySlug: "displays",
    priceMinor: 74900,
    rating: 4.3,
    reviewCount: 119,
    badge: "New",
    blurb: "A portable laser projector with automatic setup and a sharp 120-inch picture from compact spaces.",
    specs: [["Resolution", "4K pixel shift"], ["Brightness", "1200 ANSI lm"], ["Image", "40 to 120 inches"], ["Audio", "2 x 10 W"]],
    options: [],
    variants: [{ optionValues: [], onHand: 18 }],
    imageQuery: ["portable projector device", "projector lens close up", "home cinema projector"],
    imageSubject: ["projector"],
  },
  {
    slug: "lumen-ultrawide-40",
    name: "Lumen Ultrawide 40",
    brand: "LUMEN",
    category: "TVs & Displays",
    categorySlug: "displays",
    priceMinor: 129900,
    rating: 4.5,
    reviewCount: 74,
    blurb: "Two windows side by side with room to spare, and a KVM so one keyboard covers both machines.",
    specs: [["Panel", "39.7 in 5K2K IPS"], ["Aspect", "21:9"], ["Refresh", "144 Hz"], ["Extras", "KVM, 96 W USB-C"]],
    options: [],
    variants: [{ optionValues: [], onHand: 6 }],
    imageQuery: ["ultrawide monitor on desk", "curved monitor", "wide computer screen"],
    imageSubject: ["monitor", "display", "screen"],
  },
  {
    slug: "nova-portable-16",
    name: "Nova Portable 16",
    brand: "NOVA",
    category: "TVs & Displays",
    categorySlug: "displays",
    priceMinor: 27900,
    compareAtPriceMinor: 32900,
    rating: 4.2,
    reviewCount: 141,
    badge: "Deal",
    blurb: "A second screen that travels in the laptop sleeve and runs off one USB-C cable.",
    specs: [["Panel", "16 in 2.5K IPS"], ["Weight", "780 g"], ["Power", "Single USB-C"], ["Stand", "Magnetic folio"]],
    options: [],
    variants: [{ optionValues: [], onHand: 34 }],
    imageQuery: ["portable monitor screen", "computer monitor front", "monitor display on desk"],
    imageSubject: ["monitor", "display"],
  },

  // ----------------------------------------------------------- networking
  {
    slug: "orbit-mesh-wifi-7",
    name: "Orbit Mesh Wi-Fi 7",
    brand: "ORBIT",
    category: "Networking",
    categorySlug: "networking",
    priceMinor: 49900,
    compareAtPriceMinor: 57900,
    rating: 4.6,
    reviewCount: 102,
    badge: "Deal",
    blurb: "A three-node mesh designed for stable multi-gigabit coverage across a busy connected home.",
    specs: [["Standard", "Wi-Fi 7"], ["Coverage", "750 m2"], ["Ports", "2.5 GbE per node"], ["Nodes", "3 pack"]],
    options: [{ name: "Pack", values: ["2 nodes", "3 nodes"] }],
    variants: [
      { optionValues: ["2 nodes"], priceDeltaMinor: -14000, onHand: 22, imageIndex: 0 },
      { optionValues: ["3 nodes"], onHand: 16, imageIndex: 1 },
    ],
    imageQuery: ["wifi router on table", "wireless router white", "mesh router device"],
    imageSubject: ["router", "wifi", "wi-fi", "access point"],
  },
  {
    slug: "vector-travel-router",
    name: "Vector Travel Router",
    brand: "VECTOR",
    category: "Networking",
    categorySlug: "networking",
    priceMinor: 11900,
    rating: 4.4,
    reviewCount: 76,
    badge: "New",
    blurb: "A pocket router that shares hotel, phone or wired internet across every device, over WireGuard.",
    specs: [["Standard", "Wi-Fi 6"], ["VPN", "WireGuard"], ["Power", "USB-C"], ["Weight", "148 g"]],
    options: [],
    variants: [{ optionValues: [], onHand: 41 }],
    imageQuery: ["small wifi router", "travel router device", "portable router in hand"],
    imageSubject: ["router", "wifi", "wi-fi", "modem"],
  },
  {
    slug: "orbit-switch-8",
    name: "Orbit Switch 8",
    brand: "ORBIT",
    category: "Networking",
    categorySlug: "networking",
    priceMinor: 15900,
    rating: 4.5,
    reviewCount: 58,
    blurb: "Eight 2.5-gigabit ports in a fanless metal case, quiet enough to sit on the desk.",
    specs: [["Ports", "8 x 2.5 GbE"], ["Uplink", "1 x 10G SFP+"], ["Cooling", "Fanless"], ["Management", "Optional web UI"]],
    options: [],
    variants: [{ optionValues: [], onHand: 25 }],
    imageQuery: ["network switch ethernet ports", "ethernet cables in switch", "network equipment close up"],
    imageSubject: ["switch", "ethernet", "network", "cable", "port"],
  },
  {
    slug: "orbit-powerline-kit",
    name: "Orbit Powerline Kit",
    brand: "ORBIT",
    category: "Networking",
    categorySlug: "networking",
    priceMinor: 8900,
    compareAtPriceMinor: 10900,
    rating: 3.9,
    reviewCount: 143,
    badge: "Deal",
    blurb: "For the room the mesh cannot reach. Wired speed over the wiring you already have.",
    specs: [["Throughput", "Up to 2000 Mbps"], ["Ports", "2 x GbE per adapter"], ["Passthrough", "Yes"], ["Pack", "2 adapters"]],
    options: [],
    variants: [{ optionValues: [], onHand: 30 }],
    imageQuery: ["power adapter in wall socket", "electrical plug adapter", "wall outlet plug"],
    imageSubject: ["adapter", "plug", "socket", "outlet"],
  },

  // -------------------------------------------------------------- storage
  {
    slug: "nova-portable-ssd-2tb",
    name: "Nova Portable SSD 2TB",
    brand: "NOVA",
    category: "Storage",
    categorySlug: "storage",
    priceMinor: 18900,
    compareAtPriceMinor: 22900,
    rating: 4.7,
    reviewCount: 344,
    badge: "Deal",
    blurb: "A rugged pocket SSD delivering fast encrypted backups over a single USB-C cable.",
    specs: [["Read speed", "2000 MB/s"], ["Protection", "IP65"], ["Encryption", "AES-256 hardware"], ["Weight", "46 g"]],
    options: [{ name: "Capacity", values: ["1 TB", "2 TB", "4 TB"] }],
    variants: [
      { optionValues: ["1 TB"], priceDeltaMinor: -8000, onHand: 57, imageIndex: 0 },
      { optionValues: ["2 TB"], onHand: 34, imageIndex: 0 },
      { optionValues: ["4 TB"], priceDeltaMinor: 16000, onHand: 5, imageIndex: 1 },
    ],
    imageQuery: ["portable ssd in hand", "external hard drive", "solid state drive product"],
    imageSubject: ["ssd", "drive", "disk", "storage"],
  },
  {
    slug: "vector-nas-4",
    name: "Vector NAS 4",
    brand: "VECTOR",
    category: "Storage",
    categorySlug: "storage",
    priceMinor: 59900,
    rating: 4.4,
    reviewCount: 68,
    badge: "New",
    blurb: "A quiet four-bay personal cloud for automatic backups, media libraries and private sharing.",
    specs: [["Bays", "4 x SATA"], ["Networking", "2.5 GbE"], ["Memory", "8 GB ECC"], ["Drives", "Not included"]],
    options: [],
    variants: [{ optionValues: [], onHand: 12 }],
    imageQuery: ["network attached storage device", "server storage rack", "data storage hardware"],
    imageSubject: ["nas", "server", "storage"],
  },
  {
    slug: "nova-microsd-1tb",
    name: "Nova microSD 1TB",
    brand: "NOVA",
    category: "Storage",
    categorySlug: "storage",
    priceMinor: 9900,
    rating: 4.5,
    reviewCount: 512,
    blurb: "V60 sustained write, so 4K recording does not stop halfway through the take.",
    specs: [["Speed class", "V60, U3"], ["Read", "200 MB/s"], ["Write", "140 MB/s sustained"], ["Warranty", "10 years"]],
    options: [{ name: "Capacity", values: ["512 GB", "1 TB"] }],
    variants: [
      { optionValues: ["512 GB"], priceDeltaMinor: -4000, onHand: 120, imageIndex: 0 },
      { optionValues: ["1 TB"], onHand: 63, imageIndex: 0 },
    ],
    imageQuery: ["memory card close up", "sd card macro", "microsd card in hand"],
    imageSubject: ["card", "microsd", "sd "],
  },
  {
    slug: "vector-ssd-enclosure",
    name: "Vector SSD Enclosure",
    brand: "VECTOR",
    category: "Storage",
    categorySlug: "storage",
    priceMinor: 5900,
    compareAtPriceMinor: 7400,
    rating: 4.3,
    reviewCount: 231,
    badge: "Deal",
    blurb: "Tool-free aluminium housing that turns a spare NVMe stick into a 40 Gbps drive.",
    specs: [["Interface", "USB4, 40 Gbps"], ["Supports", "M.2 NVMe 2230 to 2280"], ["Body", "Machined aluminium"], ["Cable", "USB-C included"]],
    options: [],
    variants: [{ optionValues: [], onHand: 48 }],
    imageQuery: ["ssd enclosure case", "nvme drive in hand", "external drive case"],
    imageSubject: ["enclosure", "ssd", "drive", "case"],
  },

  // ---------------------------------------------------- power-accessories
  {
    slug: "orbit-gan-charger-140",
    name: "Orbit GaN Charger 140W",
    brand: "ORBIT",
    category: "Power & Accessories",
    categorySlug: "power-accessories",
    priceMinor: 9900,
    compareAtPriceMinor: 12900,
    rating: 4.7,
    reviewCount: 413,
    badge: "Deal",
    blurb: "A compact four-port charger that powers a laptop, tablet and phone without a second brick.",
    specs: [["Output", "140 W total"], ["Ports", "3 x USB-C, 1 x USB-A"], ["Protocol", "USB PD 3.1"], ["Cable", "240 W included"]],
    options: [{ name: "Plug", values: ["Type A", "Type C", "Type G"] }],
    variants: [
      { optionValues: ["Type A"], onHand: 71, imageIndex: 0 },
      { optionValues: ["Type C"], onHand: 55, imageIndex: 0 },
      { optionValues: ["Type G"], onHand: 4, imageIndex: 1 },
    ],
    imageQuery: ["usb charger plug", "power adapter white background", "wall charger close up"],
    imageSubject: ["charger", "adapter", "plug"],
  },
  {
    slug: "nova-power-bank-20k",
    name: "Nova Power Bank 20K",
    brand: "NOVA",
    category: "Power & Accessories",
    categorySlug: "power-accessories",
    priceMinor: 7900,
    rating: 4.4,
    reviewCount: 267,
    badge: "New",
    blurb: "A flight-legal 20,000 mAh battery with two-way USB-C charging and a display that tells the truth.",
    specs: [["Capacity", "20,000 mAh"], ["Output", "65 W USB-C"], ["Ports", "2 x USB-C, 1 x USB-A"], ["Display", "Percentage and watts"]],
    options: [],
    variants: [{ optionValues: [], onHand: 62 }],
    imageQuery: ["power bank in hand", "portable battery charger", "power bank on table"],
    imageSubject: ["power bank", "battery", "charger"],
  },
  {
    slug: "orbit-desk-hub",
    name: "Orbit Desk Hub",
    brand: "ORBIT",
    category: "Power & Accessories",
    categorySlug: "power-accessories",
    priceMinor: 11900,
    rating: 4.2,
    reviewCount: 129,
    blurb: "Four sockets and three USB-C ports in one weighted block, so the desk keeps one cable to the wall.",
    specs: [["Sockets", "4 mains"], ["USB", "3 x USB-C, 65 W shared"], ["Protection", "Surge, 1200 J"], ["Cable", "2 m braided"]],
    options: [],
    variants: [{ optionValues: [], onHand: 37 }],
    imageQuery: ["power strip with usb", "extension cord socket", "desk power outlet"],
    imageSubject: ["power strip", "socket", "extension", "outlet", "hub"],
  },
  {
    slug: "nova-wireless-pad",
    name: "Nova Wireless Pad",
    brand: "NOVA",
    category: "Power & Accessories",
    categorySlug: "power-accessories",
    priceMinor: 4900,
    compareAtPriceMinor: 6400,
    rating: 4.0,
    reviewCount: 288,
    badge: "Deal",
    blurb: "A magnetic 15 W pad that holds the phone at reading angle instead of flat on the desk.",
    specs: [["Output", "15 W Qi2"], ["Angle", "Adjustable 0 to 60 degrees"], ["Surface", "Recycled felt"], ["Cable", "1.5 m USB-C"]],
    options: [{ name: "Colour", values: ["Stone", "Charcoal"] }],
    variants: [
      { optionValues: ["Stone"], onHand: 83, imageIndex: 0 },
      { optionValues: ["Charcoal"], onHand: 51, imageIndex: 1 },
    ],
    imageQuery: ["wireless charging pad with phone", "qi charger on desk", "phone charging wirelessly"],
    imageSubject: ["charger", "charging", "wireless", "pad"],
  },
  {
    slug: "orbit-car-charger",
    name: "Orbit Car Charger",
    brand: "ORBIT",
    category: "Power & Accessories",
    categorySlug: "power-accessories",
    priceMinor: 3400,
    rating: 4.1,
    reviewCount: 194,
    blurb: "Two ports, 65 W, and a body short enough that nothing catches the gear lever.",
    specs: [["Output", "65 W total"], ["Ports", "2 x USB-C"], ["Protocol", "USB PD 3.0"], ["Length", "38 mm"]],
    options: [],
    variants: [{ optionValues: [], onHand: 76 }],
    imageQuery: ["car usb charger", "car charger in socket", "car phone charger"],
    imageSubject: ["charger", "car", "adapter"],
  },
];
